#!/bin/sh
#----- ノードの数, ノード内のプロセス数を指定 -----#
#PBS -l nodes=1:ppn=4
#PBS -q cluster
#----- OpenMP のスレッド数を指定する -----#
export OMP_NUM_THREADS=2
#----- 利用する NEURON の実行形式のパスとオプションを指定する -----#
NRNIV="../specials/x86_64/special -mpi"
#----- シミュレーションファイルを指定する -----#
HOC_NAME="../hoc/bench_main.hoc"
#----- シミュレーションに与えるオプション -----#
NRNOPT=\
" -c MODEL=2"\
" -c NSTIM_POS=1"\
" -c NSTIM_NUM=400"\
" -c NCELLS=256"\
" -c NSYNAPSE=10"\
" -c SYNAPSE_RANGE=1"\
" -c NETWORK=1"\
" -c STOPTIME=50"\
" -c NTHREAD=16"\
" -c MULTISPLIT=0"\
" -c SPIKE_COMPRESS=0"\
" -c CACHE_EFFICIENT=1"\
" -c SHOW_SPIKE=1"
#----- シミュレーションに与えるオプション -----#
MPIEXEC="mpiexec -mca mpi_print_stats 1"
#----- プロファイラを指定する（ gprof など） -----#
PROF=""
#----- プログラム実行の際のカレントディレクトリ -----#
cd $PBS_O_WORKDIR
#----- プログラム実行時のコマンドを出力 -----#
echo "${PROF} ${MPIEXEC} ${NRNIV} ${NRNOPT} ${HOC_NAME}"
#----- プログラムを実行 -----#
time ${PROF} ${MPIEXEC} ${NRNIV} ${NRNOPT} ${HOC_NAME}
